services:
  redis:
    image: redis:7.4.0
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--save", "60", "1"]
  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  hub:
    image: gaianet/gaia-hub:mysql.v0.1.4
    environment:
      - LOG_FILE=/logs/gaia-hub.log
      - DATABASE_URL=mysql://gaia:${MYSQL_PASSWORD}@mysql/gaia.domain
      - REDIS_URL=redis://:@redis:6379/0
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=1337
      - DB_POOL_SIZE=50
      - DB_POOL_MIN_SIZE=20
    volumes:
      - ./logs:/logs
    depends_on:
      - redis
      - mysql
  frps:
    build:
      context: ./frps
      args:
        FRP_VERSION: v0.1.1
    image: gaia-frps:0.1.1
    volumes:
      - ./frps/conf:/app/conf
    ports:
      - "7000:7000"
    depends_on:
      - hub
  openresty:
    build:
      context: ./nginx
    image: gaia-openresty
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/logs/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frps
      - hub  
  logrotate:
    image: blacklabelops/logrotate
    volumes:
      - ./logs/nginx:/logs
      - ./logs/nginx/old:/logs/old
    environment:
      - LOGS_DIRECTORIES=/logs
      - LOGROTATE_OLDDIR=/logs/old
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_INTERVAL=daily
      - LOGROTATE_COPIES=10
    depends_on:
      - openresty
  vector:
    build:
      context: ./vector
    image: gaia-vector
    volumes:
      - ./logs/nginx:/logs/nginx
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - openresty