services:
  redis:
    image: redis:7.4.0
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--save", "60", "1"]
  hub:
    build:
      context: https://github.com/GaiaNet-AI/gaia-hub.git#v0.1.1
    image: gaia-hub:0.1.1
    environment:
      - LOG_FILE=/logs/gaia-hub.log
      - DATABASE_URL=/data/gaia-domain.db
      - REDIS_URL=redis://:@redis:6379/0
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=1337
      - DB_POOL_SIZE=50
      - DB_POOL_MIN_SIZE=20
    volumes:
      - ./data/sqlite:/data
      - ./logs:/logs
    depends_on:
      - redis
  frps:
    build:
      context: ./frps
      args:
        FRP_VERSION: v0.1.1
    image: gaia-frps:0.1.1
    volumes:
      - ./frps/conf:/app/conf
    ports:
      - "7000:7000"
    depends_on:
      - hub
  openresty:
    build:
      context: ./nginx
    image: gaia-openresty
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/logs/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frps
      - hub  
